---
- name: Chekmk Installation
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
  tasks:

    - name: Creating CheckMk Folder...
      shell:
           "/usr/bin/mkdir -p /usr/lib/check_mk_agent/"

    - name: Downloading file...
      copy:
        src: /home/svcans/SW/CheckMk/check-mk-agent-2.1.0p9-1.noarch.rpm 
        dest: /usr/lib/check_mk_agent/check-mk-agent-2.1.0p9-1.noarch.rpm

    - name: Installing Chekmk..
      shell:
           "/usr/bin/yum localinstall /usr/lib/check_mk_agent/check-mk-agent-2.1.0p9-1.noarch.rpm -y"
      args:
        warn: false

    - name: Removing Temporary Files..
      ansible.builtin.file:
        state: absent
        path: /usr/lib/check_mk_agent/check-mk-agent-2.1.0p9-1.noarch.rpm

    - name: Installing needed Software...
      ansible.builtin.yum:
        name:
            python3,yum-utils,net-tools,nfs-utils,lsof
        state: latest

    - name: Downloading Falcon Package...
      copy:
        src: /home/svcans/SW/Falcon/falcon-sensor-6.58.0-15508.el8.x86_64.rpm
        dest: /tmp/falcon-sensor-6.58.0-15508.el8.x86_64.rpm

    - name: Installing Falcon Sensor...
      shell:
           "yum -y install /tmp/falcon-sensor-6.58.0-15508.el8.x86_64.rpm"
      args:
        warn: false

    - name: Setting Falcon CID...
      shell:
           "/opt/CrowdStrike/falconctl -s --cid=DEDD976AB61F41BB8AFF9C036213ECFD-ED"

    - name: Removing Temporary Files..
      ansible.builtin.file:
        state: absent
        path: /tmp/falcon-sensor-6.58.0-15508.el8.x86_64.rpm

    - name: Starting Falcon Service...
      ansible.builtin.service:
        name: falcon-sensor
        state: started

    - name: Enabling Falcon Agent...
      shell:
           "/usr/bin/systemctl start falcon-sensor"

    - name: Starting MDE Install, Downloading EDR File...
      copy:
        src: /home/svcans/SW/MDE/mde_linux_edr_diy.sh 
        dest: /tmp/mde_linux_edr_diy.sh 

    - name: Downloading Onboarding Script for MDE...
      copy:
        src: /home/svcans/SW/MDE/MicrosoftDefenderATPOnboardingLinuxServer.py
        dest: /tmp/MicrosoftDefenderATPOnboardingLinuxServer.py

    - name: Adding Microsoft Repository for MDE...
      shell:
           "/usr/bin/yum-config-manager --add-repo=https://packages.microsoft.com/config/rhel/8/prod.repo"
      args:
        warn: false

    - name: Importing Packages for MDE...
      shell:
           "/usr/bin/rpm --import http://packages.microsoft.com/keys/microsoft.asc"
      args:
        warn: false
    
    - name: Installing MDE ...
      shell:
           "/usr/bin/yum -y install mdatp"
      args:
        warn: false

    - name: Checking MDE CID...
      shell:
           "/usr/bin/mdatp health --field org_id"
      args:
        warn: false

    - name: Adding MDE CID...
      shell:
           "/usr/bin/python3 /tmp/MicrosoftDefenderATPOnboardingLinuxServer.py"
      args:
        warn: false

    - name: Checking MDE CID...
      shell:
           "/usr/bin/mdatp health --field org_id"
      args:
        warn: false

    - name: Checking Real Time Protection Status...
      shell:
           "/usr/bin/mdatp health --field healthy"
      args:
        warn: false

    - name: Downloading eicar file for MDE Testing...
      shell:
           "/usr/bin/curl -o /tmp/eicar.com.txt https://www.eicar.org/download/eicar.com.txt -k"
      args:
        warn: false

    - name: Checking for threats, MDE dummy file...
      shell:
           "/usr/bin/mdatp threat list"
      args:
        warn: false

    - name: Updating definitions for MDE...
      shell:
           "/usr/bin/sh /tmp/mde_linux_edr_diy.sh"
      args:
        warn: false

    - name: Uploading Tanium Package....
      copy:
        src: /home/svcans/SW/Tanium/TaniumClient-7.4.9.1077-1.rhe8.x86_64.rpm
        dest: /tmp/TaniumClient-7.4.9.1077-1.rhe8.x86_64.rpm
        owner: root
        group: root
        mode: 0755
        remote_src: false

    - name: Installing Tanium...
      shell:
           "rpm -ivh /tmp/TaniumClient-7.4.9.1077-1.rhe8.x86_64.rpm"

    - name: Copying Tanium-init.dat to the server...
      copy:
        src: /home/svcans/SW/Tanium/tanium-init.dat
        dest: /opt/Tanium/TaniumClient/tanium-init.dat
        owner: root
        group: root
        mode: 0644
        remote_src: false

    - name: Starting Tanium Service..
      shell:
           "systemctl start taniumclient.service"

    - name: Enabling Tanium Service..
      shell:
           "systemctl enable taniumclient.service"

    - name: Removing Temporary Files..
      ansible.builtin.file:
        state: absent
        path: /tmp/TaniumClient-7.4.9.1077-1.rhe8.x86_64.rpm
