---

- name: Installing SSM..
  hosts: all
  become: yes
  tasks:

  - name: Uploading SSM Package....
    copy:
      src: /home/svcans/SW/SSM/amazon-ssm-agent.rpm
      dest: /tmp/amazon-ssm-agent.rpm
      owner: root
      group: root
      mode: 0755
      remote_src: false

  - name: Installing SSM...
    shell:
         "yum install -y /tmp/amazon-ssm-agent.rpm"

  - name: Stopping SSM Service..
    shell:
         "systemctl stop amazon-ssm-agent"

  - name: Registeiring Instance on SSM Console...
    shell:
         "echo 'yes' |sudo -E amazon-ssm-agent -register -code '/tN0KxJNaR+7K5dxSK8l' -id '874ec54c-0e58-4007-8fed-93189c6deea8' -region 'us-east-1'"

  - name: Starting SSM...
    shell:
         "systemctl start amazon-ssm-agent"

  - name: Removing Temporary Files..
    ansible.builtin.file:
      state: absent
      path: /tmp/amazon-ssm-agent.rpm
