---

- name: Installing SSM..
  hosts: all
  become: yes
  tasks:

  - name: Uploading SSM Package....
    copy:
      src: /home/svcans/SW/SSM/amazon-ssm-agent.deb
      dest: /tmp/amazon-ssm-agent.deb
      owner: root
      group: root
      mode: 0755
      remote_src: false

  - name: Installing SSM...
    shell:
         "dpkg -i /tmp/amazon-ssm-agent.deb"

  - name: Stopping SSM Service..
    shell:
         "service amazon-ssm-agent stop"

  - name: Registeiring Instance on SSM Console...
    shell:
         "sudo -E amazon-ssm-agent -register -code 'Af5X000dyKRd3IPKUTkT' -id '56ce21cd-aef4-48c6-a028-7b4f6d154a03' -region 'us-east-1'"

  - name: Starting SSM...
    shell:
         "service amazon-ssm-agen startt"

  - name: Removing Temporary Files..
    ansible.builtin.file:
      state: absent
      path: /tmp/amazon-ssm-agent.deb
