---

- name: Installing Tanium..
  hosts: all
  become: yes
  tasks:

  - name: Uploading Tanium Package....
    copy:
      src: /home/svcans/SW/Tanium/taniumclient_7.4.9.1077-ubuntu22_amd64.deb
      dest: /tmp/taniumclient_7.4.9.1077-ubuntu22_amd64.deb
      owner: root
      group: root
      mode: 0755
      remote_src: false

  - name: Installing Tanium...
    shell:
         "dpkg -i /tmp/taniumclient_7.4.9.1077-ubuntu22_amd64.deb"

  - name: Copying Tanium-init.dat to the server...
    copy:
      src: /home/svcans/SW/Tanium/tanium-init.dat
      dest: /opt/Tanium/TaniumClient/tanium-init.dat
      owner: root
      group: root
      mode: 0644
      remote_src: false

  - name: Starting Tanium Service..
    shell:
         "service taniumclient start"

  - name: Enabling Tanium Service..
    shell:
         "update-rc.d taniumclient defaults"

  - name: Removing Temporary Files..
    ansible.builtin.file:
      state: absent
      path: /tmp/taniumclient_7.4.9.1077-ubuntu22_amd64.deb
