---

- name: Installing Cisco Secure Workload..
  hosts: all
  become: yes
  tasks:

  - name:  Installing UNZIP package
    ansible.builtin.yum:
      name: unzip
      state: latest

  - name:  Installing LSOF package
    ansible.builtin.yum:
      name: lsof
      state: latest

  - name:  Installing IPTABLES package
    ansible.builtin.yum:
      name: iptables-utils
      state: latest

  - name: Uploading CSW Package....
    copy:
      src: /home/svcans/SW/CSW/tetration_installer_livingstonpov_enforcer_linux_tes.sh
      dest: /tmp/tetration_installer_livingstonpov_enforcer_linux_tes.sh
      owner: root
      group: root
      mode: 0755
      remote_src: false

  - name: Installing CSW...
    shell:
         "bash /tmp/tetration_installer_livingstonpov_enforcer_linux_tes.sh"

  - name: Starting CSW Service..
    shell:
         "systemctl start csw-agent"

  - name: Enabling CSW Service..
    shell:
         "systemctl enable csw-agent"

  - name: Removing Temporary Files..
    ansible.builtin.file:
      state: absent
      path: /tmp/tetration_installer_livingstonpov_enforcer_linux_tes.sh
