---
- name: Chekmk Installation
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
  tasks:

    - name: Creating CheckMk Folder...
      shell:
           "/usr/bin/mkdir -p /usr/lib/check_mk_agent/"

    - name: Downloading file...
      copy:
        src: /home/svcans/SW/CheckMk/check-mk-agent-2.1.0p9-1.noarch.rpm 
        dest: /usr/lib/check_mk_agent/check-mk-agent-2.1.0p9-1.noarch.rpm

    - name: Installing Chekmk..
      shell:
           "/usr/bin/yum localinstall /usr/lib/check_mk_agent/check-mk-agent-2.1.0p9-1.noarch.rpm -y"
      args:
        warn: false
