---

- hosts: all
  become: yes
  tasks:
    - name: Disable Root SSH Logins
      lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^PermitRootLogin'
            line: "PermitRootLogin no"
            state: present
            backup: yes
      notify:
        - restart ssh

    - name: Enable Kerberos Auth
      lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^KerberosAuthentication'
            line: "KerberosAuthentication yes"
            state: present
            backup: yes
      notify:
        - restart ssh

  handlers:
  - name: restart ssh
    service:
      name: sshd
      state: restarted        
