---

- hosts: all
  become: yes
  tasks:
    - name: Change sysop password
      user:
        name: sysop
        password: "$6$HxFoz8us$64u6QORqrZzevFRsgRAMnZxC2WmmGjiBIXioE98JOTx5z2enB0wk4YyGuVb9ocLvYvollIAGgM70aWqKyXiEO/"
