---

- hosts: all
  become: yes
  tasks:
          
  - name: Reboot the machine
    shell: "sleep 2 && reboot"

    async: 1
    poll: 0

  - name: Wait for the machine to come back online
    wait_for_connection:
      connect_timeout: 60
      sleep: 120
      delay: 120
      timeout: 300
