---
- name: Falcon Sensor Installation
  hosts: all
  become: yes
  vars:
    mynfs: "172.23.193.66:/ansfs"
    mountpoint: "/linuxoneoff"
    permission: '0777'
    myopts: 'rw,sync'
  tasks:

    - name: Mounting Remote Share...
      ansible.posix.mount:
        src: "{{ mynfs }}"
        path: "{{ mountpoint }}"
        fstype: nfs
        opts: "{{ myopts }}"
        state: mounted

    - name: Installing Falcon Sensor...
      shell:
           "yum -y install /linuxoneoff/falcon-sensor-6.58.0-15508.el9.x86_64.rpm"
      args:
        warn: false

    - name: Setting CID...
      shell:
           "/opt/CrowdStrike/falconctl -s --cid=DEDD976AB61F41BB8AFF9C036213ECFD-ED"

    - name: Starting Service...
      shell:
           "/usr/bin/sudo -u root /usr/sbin/service falcon-sensor start"

    - name: Starting Service Second Attempt...
      shell:
           "/usr/bin/sudo -u root /usr/bin/systemctl start falcon-sensor"
