---

- name: Installing SSM..
  hosts: all
  become: yes
  tasks:

  - name: Uploading GuardiCore Package....
    copy:
      src: /home/svcans/SW/GC/gc-guest-agent-x86_64-rhel-6.rpm
      dest: /tmp/gc-guest-agent-x86_64-rhel-6.rpm
      owner: root
      group: root
      mode: 0755
      remote_src: false

  - name: Installing Guardicore Agent...
    ansible.builtin.script: /home/svcans/ansible_tutorial/SCRIPTS/Install_GC_RHEL.sh
