---

- name: Removing File
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:

  - name: Remove file (delete file)
    ansible.builtin.file:
      path: /tmp/falcon-sensor-6.58.0-15508.el9.x86_64.rpm
      state: absent
